batch_size: 128
client_lr: 0.5126671656932206
client_momentum: 0.7868091160130161
client_optimizer: "sgd"
client_sampling_frac: 1.
client_weight_decay: 0.
dataset_name: "cifar10-pretrained"
debug: false
eval_dataset: "test"
gaussian_noise_sigma: 0.0
global_rounds: 80
l2_clip: 8.18466751651911
local_epochs: 1
model_name: "CIFAR10_linear_classifier"
num_clients: 10
per_round_eval_frac: 1.
quantization: 32
run_only_batches: true
server_lr: 0.720105481946425
server_momentum: 0.7558152080559885
skellam_noise_sigma: 0.515728157434619
skellam_num_clients: 10
testset_frac: 0.2
train_test_split_seed: 2303
use_skellam: "all"
validation_frac: 0.3