batch_size: 128
client_lr: 0.9335235959847616
client_momentum: 0.2511313192557987
client_optimizer: "sgd"
client_sampling_frac: 1.
client_weight_decay: 0.
dataset_name: "cifar10-pretrained"
debug: false
eval_dataset: "test"
gaussian_noise_sigma: 0.0
global_rounds: 160
l2_clip: 11.296039873122936
local_epochs: 1
model_name: "CIFAR10_linear_classifier"
num_clients: 10
per_round_eval_frac: 1.
quantization: 32
run_only_batches: true
server_lr: 0.19838752352521985
server_momentum: 0.8872718414851855
skellam_noise_sigma: 0.6219751014998873
skellam_num_clients: 10
testset_frac: 0.2
train_test_split_seed: 2303
use_skellam: "all"
validation_frac: 0.3