batch_size: 128
client_lr: 0.44218819688283906
client_momentum: 0.8576349319211244
client_optimizer: "sgd"
client_sampling_frac: 1.
client_weight_decay: 0.
dataset_name: "cifar10-pretrained"
debug: false
eval_dataset: "test"
gaussian_noise_sigma: 0.0
global_rounds: 20
l2_clip: 13.327501972205816
local_epochs: 1
model_name: "CIFAR10_linear_classifier"
num_clients: 10
per_round_eval_frac: 1.
quantization: 32
run_only_batches: true
server_lr: 0.794474821365726
server_momentum: 0.8080472731217668
skellam_noise_sigma: 0.4471462381075494
skellam_num_clients: 10
testset_frac: 0.2
train_test_split_seed: 2303
use_skellam: "all"
validation_frac: 0.3