batch_size: 256
client_lr: 0.5327954145807728
client_momentum: 0.8381846089908012
client_optimizer: "sgd"
client_sampling_frac: 1.
client_weight_decay: 0.
dataset_name: "cifar10-pretrained"
debug: false
eval_dataset: "test"
gaussian_noise_sigma: 0.0
global_rounds: 40
l2_clip: 17.680244288061157
local_epochs: 1
model_name: "CIFAR10_linear_classifier"
num_clients: 10
per_round_eval_frac: 1.
quantization: 32
run_only_batches: false
server_lr: 0.9767288260106182
server_momentum: 0.4740713942254997
skellam_noise_sigma: 2.3143545265829286
skellam_num_clients: 10
testset_frac: 0.2
train_test_split_seed: 2303
use_skellam: "all"
validation_frac: 0.3
