batch_size: 256
client_lr: 0.41810921089401704
client_momentum: 0.6518649664624732
client_optimizer: "sgd"
client_sampling_frac: 1.
client_weight_decay: 0.
dataset_name: "cifar10-pretrained"
debug: false
eval_dataset: "test"
gaussian_noise_sigma: 0.0
global_rounds: 10
l2_clip: 13.374296258740875
local_epochs: 1
model_name: "CIFAR10_linear_classifier"
num_clients: 10
per_round_eval_frac: 1.
quantization: 32
run_only_batches: false
server_lr: 0.4335309856243086
server_momentum: 0.6811125443556506
skellam_noise_sigma: 1.2100643239671252
skellam_num_clients: 10
testset_frac: 0.2
train_test_split_seed: 2303
use_skellam: "all"
validation_frac: 0.3
