batch_size: 256
client_lr: 0.4089146225987706
client_momentum: 0.8178158318071244
client_optimizer: "sgd"
client_sampling_frac: 1.
client_weight_decay: 0.
dataset_name: "cifar10-pretrained"
debug: false
eval_dataset: "test"
gaussian_noise_sigma: 0.0
global_rounds: 160
l2_clip: 9.542646531569936
local_epochs: 1
model_name: "CIFAR10_linear_classifier"
num_clients: 10
per_round_eval_frac: 1.
quantization: 32
run_only_batches: false
server_lr: 0.9485318423184388
server_momentum: 0.39422665919146416
skellam_noise_sigma: 4.575767579079621
skellam_num_clients: 10
testset_frac: 0.2
train_test_split_seed: 2303
use_skellam: "all"
validation_frac: 0.3
