batch_size: 512
client_lr: 0.36505448102655774
client_momentum: 0.4651066004208093
client_optimizer: "sgd"
client_sampling_frac: 1.
client_weight_decay: 0.
dataset_name: "fashion_mnist"
debug: false
eval_dataset: "test"
gaussian_noise_sigma: 0.0
global_rounds: 20
l2_clip: 19.075718447812072
local_epochs: 1
model_name: "MNIST_CNN"
num_clients: 10
per_round_eval_frac: 1.
quantization: 32
run_only_batches: false
server_lr: 0.993130389165448
server_momentum: 0.19953416390099976
skellam_noise_sigma: 2.1573279118783493
skellam_num_clients: 10
testset_frac: 0.2
train_test_split_seed: 2303
use_skellam: "all"
validation_frac: 0.3
