batch_size: null
client_lr: 0.9559925826998584
client_momentum: 0.32670681774988775
client_optimizer: "sgd"
client_sampling_frac: 1.
client_weight_decay: 0.
dataset_name: "income"
debug: false
eval_dataset: "test"
gaussian_noise_sigma: 0.0
global_rounds: 10
l2_clip: 9.245417946473202
local_epochs: 1
local_sampling_frac: 0.05
model_name: "Income_classifier"
num_clients: 51
per_round_eval_frac: 1.
quantization: 32
run_only_batches: true
server_lr: 0.9669057242252956
server_momentum: 0.8123284278994534
skellam_noise_sigma: 0.22685402549232628
skellam_num_clients: 51
testset_frac: 0.2
train_test_split_seed: 2303
use_skellam: "all"
validation_frac: 0.3
