batch_size: null
client_lr: 0.5268109799367644
client_momentum: 0.8013458105499918
client_optimizer: "sgd"
client_sampling_frac: 1.
client_weight_decay: 0.
dataset_name: "income"
debug: false
eval_dataset: "test"
gaussian_noise_sigma: 0.0
global_rounds: 10
l2_clip: 14.001718342519004
local_epochs: 1
local_sampling_frac: 0.05
model_name: "Income_classifier"
num_clients: 51
per_round_eval_frac: 1.
quantization: 32
run_only_batches: false
server_lr: 0.9446562119604196
server_momentum: 0.5787398880590188
skellam_noise_sigma: 0.5164636682468154
skellam_num_clients: 51
testset_frac: 0.2
train_test_split_seed: 2303
use_skellam: "all"
validation_frac: 0.3
